### ISSUE TITLE
Production ready docker image

### ISSUE THREAD

**Issue by kokaz** [FreshRSS/docker-freshrss#3]
Hi,

As this repo is for development purpose only, if you need a production ready image I made one here:
https://github.com/kokaz/docker-freshrss

Let me know if you have things to improve. The image contains the beta version with all recommended and required PHP extensions.

**Comment by aledeg** [comment]
Nice!

**Comment by Alkarex** [comment]
For reference https://github.com/FreshRSS/FreshRSS/pull/963
