### ISSUE TITLE
FreshRSS error: FreshRSS requires PHP 5.3.8+!

### ISSUE THREAD

**Issue by perrinjerome** [FreshRSS/docker-freshrss#4]
This image is now using a too old php and accessing http://localhost:8080/ just display `FreshRSS error: FreshRSS requires PHP 5.3.8+!`

I tried a bit to update this image and gave up, thinking it might be easier to also use https://github.com/FreshRSS/docker-freshrss-production to get a development instance.

For the records I did 5db960c (which is basically `docker-freshrss-production` ), I can use it for development but I don't have the pre-loaded database.

**Comment by Alkarex** [comment]
Yes, the Docker images are outdated. I will try to prioritize making new versions.

**Comment by Frenzie** [comment]
Never tried these, but could it be as simple as just changing centos6 to centos7? (That's PHP 5.4 iirc.)

https://github.com/FreshRSS/docker-freshrss/blob/8f5857f689f7b2eca2f8a5dc7b22ea1008bfee51/Dockerfile#L1

**Comment by perrinjerome** [comment]
Yes I tried that, but unfortunately it was not so easy.
Next problem was that `mysql` command was not found.
Next problem was that `service` command was not found, services are now based on systemd.

I went as far as:
```diff
diff --git a/Dockerfile b/Dockerfile
index 8deafaa..43135cd 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,9 +1,9 @@
-FROM centos:centos6
+FROM centos:centos7
 MAINTAINER Marien Fressinaud <dev@marienfressinaud.fr>

 # Install packages
 RUN yum update -y
-RUN yum install -y vim httpd mysql-server php php-mysql php-pdo php-xml
+RUN yum install -y vim httpd mysql-server php php-mysql php-pdo php-xml mysql initscripts

 # Configure the database
 ADD init.sh /tmp/init.sh
```

which still failed in the build step:

```
$ docker build -t marienfressinaud/freshrss .
Sending build context to Docker daemon  287.7kB
Step 1/14 : FROM centos:centos7
 ---> ff426288ea90
Step 2/14 : MAINTAINER Marien Fressinaud <dev@marienfressinaud.fr>
 ---> Using cache
 ---> 79a2efb89c83
Step 3/14 : RUN yum update -y
 ---> Using cache
 ---> ae3c116e9097
Step 4/14 : RUN yum install -y vim httpd mysql-server php php-mysql php-pdo php-xml mysql initscripts
 ---> Using cache
 ---> f8f4b3252a1e
Step 5/14 : ADD init.sh /tmp/init.sh
 ---> Using cache
 ---> f95e7e3b8108
Step 6/14 : ADD dump_freshrss.sql /tmp/dump_freshrss.sql
 ---> Using cache
 ---> b3ae01d733ce
Step 7/14 : RUN chmod 775 /tmp/init.sh
 ---> Using cache
 ---> ea2619f7d14f
Step 8/14 : RUN service mysqld start ; ./tmp/init.sh ; service mysqld stop
 ---> Running in 37b3a5a5865c
Redirecting to /bin/systemctl start mysqld.service
Failed to get D-Bus connection: Operation not permitted
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)'
Check that mysqld is running and that the socket: '/var/lib/mysql/mysql.sock' exists!
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)'
Check that mysqld is running and that the socket: '/var/lib/mysql/mysql.sock' exists!
Redirecting to /bin/systemctl stop mysqld.service
Failed to get D-Bus connection: Operation not permitted
The command '/bin/sh -c service mysqld start ; ./tmp/init.sh ; service mysqld stop' returned a non-zero code: 1
```

this is where I gave up, thinking that `docker-freshrss-production` was enough and maybe there was no need for two different dockerfiles.

**Comment by Alkarex** [comment]
I plan to restart completely using `php:7.2-apache` instead of a CentOS base, together with a better strategy for data and logs.

**Comment by Frenzie** [comment]
@perrinjerome Oh right, systemd. I still don't comprehend that stuff. What I liked about Linux when I switched is how easy it was compared to Windows. :-P

systemctl is pretty similar, at least in the start/stop/restart part of it.

**Comment by Alkarex** [comment]
I have a new Docker image coming tonight

**Comment by Alkarex** [comment]
Tests of the new Docker image welcome https://github.com/FreshRSS/FreshRSS/pull/1813
The online version (hub.docker.com) is not yet available, but there is a command to build locally, and it is quite small < 80MB and fast.

**Comment by Alkarex** [comment]
* https://github.com/FreshRSS/FreshRSS/tree/dev/Docker
* https://hub.docker.com/r/freshrss/freshrss/
* https://cloud.docker.com/app/freshrss/repository/docker/freshrss/freshrss
